@baseUrl = http://localhost:8080

POST {{baseUrl}}/receipts/process
Content-Type: application/json

{
    "retailer": "Walgreens",
    "purchaseDate": "2022-01-02",
    "purchaseTime": "08:13",
    "total": "2.65",
    "items": [
        {
            "shortDescription": "Pepsi - 12-oz",
            "price": "1.25"
        },
        {
            "shortDescription": "Dasani",
            "price": "1.40"
        }
    ]
}

### Git hub provided example 1
POST {{baseUrl}}/receipts/process
Content-Type: application/json

{
  "retailer": "Target",
  "purchaseDate": "2022-01-01",
  "purchaseTime": "13:01",
  "items": [
    {
      "shortDescription": "Mountain Dew 12PK",
      "price": "6.49"
    },{
      "shortDescription": "Emils Cheese Pizza",
      "price": "12.25"
    },{
      "shortDescription": "Knorr Creamy Chicken",
      "price": "1.26"
    },{
      "shortDescription": "Doritos Nacho Cheese",
      "price": "3.35"
    },{
      "shortDescription": "   Klarbrunn 12-PK 12 FL OZ  ",
      "price": "12.00"
    }
  ],
  "total": "35.35"
}


### get the reciept points example 1
GET {{baseUrl}}/receipts/hY26VWq7zAZ4EDAz/points
Content-Type: application/json




### Git hub provided example 2
POST {{baseUrl}}/receipts/process
Content-Type: application/json

{
  "retailer": "M&M Corner Market",
  "purchaseDate": "2022-03-20",
  "purchaseTime": "14:33",
  "items": [
    {
      "shortDescription": "Gatorade",
      "price": "2.25"
    },{
      "shortDescription": "Gatorade",
      "price": "2.25"
    },{
      "shortDescription": "Gatorade",
      "price": "2.25"
    },{
      "shortDescription": "Gatorade",
      "price": "2.25"
    }
  ],
  "total": "9.00"
}


### get the reciept points example 2
GET {{baseUrl}}/receipts/LYJJ7PovMQvgE3E1/points
Content-Type: application/json


### Random Test 3
POST {{baseUrl}}/receipts/process
Content-Type: application/json

{
  "retailer": "Walmart",
  "purchaseDate": "2023-06-15",
  "purchaseTime": "14:30",
  "items": [
    {
      "shortDescription": "Bread",
      "price": "2.50"
    },
    {
      "shortDescription": "Peanut Butter",
      "price": "5.75"
    },
    {
      "shortDescription": "Grapes Seedless",
      "price": "4.25"
    },
    {
      "shortDescription": "Organic Honey 500g",
      "price": "10.00"
    }
  ],
  "total": "22.50"
}



### get the reciept points example 1
GET {{baseUrl}}/receipts/uMHy1mQgoYCkzWM3/points
Content-Type: application/json




### Edge Case Test 
POST {{baseUrl}}/receipts/process
Content-Type: application/json

{
  "retailer": "7-Eleven",
  "purchaseDate": "2024-02-29",
  "purchaseTime": "15:59",
  "items": [
    {
      "shortDescription": "Milk",
      "price": "3.25"
    },
    {
      "shortDescription": "   Eggs 12pk   ",
      "price": "2.99"
    },
    {
      "shortDescription": "Banana",
      "price": "0.55"
    },
    {
      "shortDescription": "Peanut Butter 16oz",
      "price": "4.50"
    },
    {
      "shortDescription": "Chips",
      "price": "1.75"
    }
  ],
  "total": "13.04"
}




### get the reciept points example 1
GET {{baseUrl}}/receipts/ycfPbjrHb2YrYThy/points
Content-Type: application/json
